### ISSUE TITLE
scroll-amount not firing on mobile devices

### ISSUE THREAD

**Issue by cedi-code** [nobrefelipe/vue-css-variable-parallax#2]
While running the site on "mobile preview", the variable scroll-amount doesn't apear to change or even apear..

It can be seen on the codepen demo on full page:  
https://codepen.io/nobrefelipe/full/aqYyOy/
![grafik](https://user-images.githubusercontent.com/34920379/43993107-f06e1526-9d88-11e8-891e-4d5281fac1e3.png)

**Comment by nobrefelipe** [comment]
Hi @cedi-code  this is a voluntary thing. Mobile parallax is disabled by default. I will enable it and add an option to disable it.
Thanks for your support

**Comment by nobrefelipe** [comment]
Hi @cedi-code  this is fixed now and you can use `mobileOff` as argument to disable the effect on  small devices

**Comment by cedi-code** [comment]
Thank you very much! 
I appreciate the support and apologize for my lack of knowledge on this topic.

Thanks to this "plugin",  it inspired me to do my own effect on my [Portfolio](https://cedricgirardin.ch/#/)
